<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- ASP.NET Core turlari (IFormFile, SignalR Hub, IHostedService, DataProtection, ILogger) -->
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SecureGate.Domain\SecureGate.Domain.csproj" />
    <ProjectReference Include="..\SecureGate.Data\SecureGate.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FaceAiSharp" Version="0.5.23" />
    <PackageReference Include="FaceAiSharp.Bundle" Version="0.5.23" />
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260427" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.10" />
  </ItemGroup>

</Project>
